spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:47.98.102.29}
    port: ${RABBIT_MQ_PORT:15672}
    username: ${RABBIT_MQ_USERNAME:xia}
    password: ${RABBIT_MQ_PASSWORD:123456}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info